### ISSUE TITLE
Write a blog post about 'Altogic + Intercom'

### ISSUE THREAD

**Issue by zinedkaloc** [altogic/hacktoberfest#11]
# 👋🏻 Introduction

Altogic is a powerful **backend as a service platform**, helping developers and businesses to design, deploy and manage scalable backend apps. We want to create a top-notch developer experience by developing blog posts and examples for novice Altogic developers.

### 🖼 Scope

The scope of the task is writing a blog post about `Altogic + Intercom`. The main topic of your article should be explaining how to use Altogic with Intercom.

### 🧰 Requirement definitions

- Your article should be at least 1000 words long.
- Your article must be publicly available to everyone. (Medium, Dev.to, HashNode, etc.)
- Your article should have a good look. ✨ (You can use titles, images, screenshots, etc.)
- Your article must have a link to [Altogic website](https://www.altogic.com).
- Your article must contain `Altogic + Intercom` keywords.

### ✅ Tasks

- [ ]  Write a blog post about `Altogic + Intercom`.
- [ ]  Post the blog post on a platform or website you like best. (Medium, Dev.to, HashNode, etc.)
- [ ]  Submit PR to [altogic/hacktoberfest](https://github.com/altogic/hacktoberfest) with a link to your article.
- [ ]  Share the article on your social channels.

🎯 If you are interested to work on this issue, please let us know about the assignment.

🆘 If you need help, join our [Discord server](https://discord.gg/ERK2ssumh8) and contact us.
